// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnneukqfxbosalichimv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubmV1a3FmeGJvc2FsaWNoaW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDY5ODYsImV4cCI6MjA2NDEyMjk4Nn0.bfblWWoZLxUDJ4sa7N1I-jwwKOagDZgQ4dkLsQGkaWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);